package ssm;

/**
 * This class provides the types that will be need to be loaded from
 * language-dependent XML files.
 * 
 * @author McKilla Gorilla & Chris Grasing
 */
public enum LanguagePropertyType {
    // TITLE FOR WINDOW TITLE BAR
    // TITLE FOR WINDOW TITLE BAR
    TITLE_WINDOW,
    
    // APPLICATION TOOLTIPS FOR BUTTONS
    TOOLTIP_NEW_SLIDE_SHOW,
    TOOLTIP_LOAD_SLIDE_SHOW,
    TOOLTIP_SAVE_SLIDE_SHOW,
    TOOLTIP_VIEW_SLIDE_SHOW,
    TOOLTIP_EXIT,
    TOOLTIP_ADD_SLIDE,
    TOOLTIP_REMOVE_SLIDE,
    TOOLTIP_MOVE_UP,
    TOOLTIP_MOVE_DOWN,
    TOOLTIP_PREVIOUS_SLIDE,
    TOOLTIP_NEXT_SLIDE,
    TOOLTIP_NAME_SLIDE_SHOW,
    YES_BUTTON_TEXT,
    NO_BUTTON_TEXT,
    CANCEL_BUTTON_TEXT,
    SAVE_LABEL_TEXT,
    NAME_LABEL_TEXT,
    
    // DEFAULT VALUES
    DEFAULT_IMAGE_CAPTION,
    DEFAULT_SLIDE_SHOW_TITLE,
    
    // STUFF FOR THE SLIDE SHOW VIEWER
    NEXT_BUTTON_TEXT,
    PREVIOUS_BUTTON_TEXT,
    TOOLTIP_NEXT_BUTTON,
    TOOLTIP_PREVIOUS_BUTTON,
    
    // UI LABELS
    LABEL_CAPTION,
    

      
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    ERROR_SAVE_SLIDESHOW_TITLE,
    ERROR_SAVE_SLIDESHOW_DIALOGUE,
    ERROR_IMAGE_RETRIEVAL_TITLE,
    ERROR_IMAGE_RETRIEVAL_DIALOGUE,
    ERROR_LOADING_JSON_TITLE,
    ERROR_LOADING_JSON_DIALOGUE
}
